#+title: czm-tex-jump.el: Jump to references in a TeX buffer using avy
#+author: Paul Nelson

* Overview
This package provides a command =czm-tex-jump= that supports following references in a TeX buffer using [[https://github.com/abo-abo/avy][avy]].  The functionality is roughly similar to that of [[https://www.gnu.org/software/emacs/manual/html_node/reftex/Viewing-Cross_002dReferences.html][reftex-view-crossref]], but useful in situations where reftex doesn't work (e.g., indirect buffers and org latex src blocks), and it's implemented using [[https://github.com/abo-abo/avy][avy]], so you don't have to spend keystrokes on navigation.

* Configuration
This package requires [[https://github.com/ultronozm/czm-tex-util.el][czm-tex-util.el]]], so install that first.

Download this repository, install using =M-x package-install-file= (or package-vc-install, straight, elpaca, ...), and add something like the following to your [[https://www.emacswiki.org/emacs/InitFile][init file]]:
#+begin_src elisp
(use-package czm-tex-jump
  :bind
  (:map LaTeX-mode-map
	("s-r" . czm-tex-jump)))
#+end_src
Replace "s-r" with your preferred key binding.

* Usage
When you run =czm-tex-jump=, you will be prompted [[https://github.com/abo-abo/avy][avy]]-style to select a reference to follow.  By supplying one or more prefix arguments to this command, you can change the behavior: see the documentation (=C-h f czm-tex-jump=) for details.
